# Generated by Django 5.1.2 on 2025-05-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='number_of_employees',
            field=models.IntegerField(blank=True, help_text='Number of employees (if known)', null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='chamber_of_commerce_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='businesscategory',
            name='chamber_of_commerce_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
