# Generated by Django 4.2.22 on 2025-07-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_address_latitude_address_longitude_business_extra"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="downtown_frederick_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="ID from Downtown Frederick directory (permalink slug)",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
